// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylShwDabG157CSvDw-NRNH0e6KyLKiAU',
    appId: '1:65174667168:web:cfa9cc70456a72a4242ec5',
    messagingSenderId: '65174667168',
    projectId: 'navigation-38d3a',
    authDomain: 'navigation-38d3a.firebaseapp.com',
    storageBucket: 'navigation-38d3a.firebasestorage.app',
    measurementId: 'G-9F24SR04RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLrt8PPkhis1uY4wjncrgMHSYJMm3AoI',
    appId: '1:65174667168:android:16c419953df67bc0242ec5',
    messagingSenderId: '65174667168',
    projectId: 'navigation-38d3a',
    storageBucket: 'navigation-38d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADpXxreSOK3iSIQd0hGRdn8wMG7aWitA',
    appId: '1:65174667168:ios:62f5cc05d12c5015242ec5',
    messagingSenderId: '65174667168',
    projectId: 'navigation-38d3a',
    storageBucket: 'navigation-38d3a.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADpXxreSOK3iSIQd0hGRdn8wMG7aWitA',
    appId: '1:65174667168:ios:62f5cc05d12c5015242ec5',
    messagingSenderId: '65174667168',
    projectId: 'navigation-38d3a',
    storageBucket: 'navigation-38d3a.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAylShwDabG157CSvDw-NRNH0e6KyLKiAU',
    appId: '1:65174667168:web:15468b83b56464fd242ec5',
    messagingSenderId: '65174667168',
    projectId: 'navigation-38d3a',
    authDomain: 'navigation-38d3a.firebaseapp.com',
    storageBucket: 'navigation-38d3a.firebasestorage.app',
    measurementId: 'G-XMQPC6C56N',
  );
}
